// Data statis + seed untuk Radar Pantai Bali.
// Semua teks Bahasa Indonesia. Data in-memory dulu.
// TODO(backend): ganti seed ini dengan fetch API (laporan + aksi).

// Koordinat bibir pantai tiap titik (disnap ke garis natural=coastline
// OpenStreetMap, diverifikasi via Overpass API). Dipakai pemilih pantai di
// form Lapor dan pusat heatmap di tab Peta.
export const BEACHES = [
  { name: "Kuta", lat: -8.7186, lng: 115.1688 },
  { name: "Seminyak", lat: -8.6843, lng: 115.1523 },
  { name: "Canggu", lat: -8.6602, lng: 115.1308 },
  { name: "Sanur", lat: -8.7106, lng: 115.2574 },
  { name: "Jimbaran", lat: -8.781, lng: 115.1636 },
  { name: "Nusa Dua", lat: -8.7883, lng: 115.2303 },
  { name: "Melasti", lat: -8.84829, lng: 115.15757 },
  { name: "Padang Padang", lat: -8.8112, lng: 115.1036 },
  { name: "Pandawa", lat: -8.8455, lng: 115.1866 },
  { name: "Virgin Beach", lat: -8.5607, lng: 115.4569 },
  { name: "Suluban", lat: -8.8234, lng: 115.0854 },
  { name: "Balangan", lat: -8.792, lng: 115.1234 },
  { name: "Legian", lat: -8.7039, lng: 115.1647 },
  { name: "Batu Bolong", lat: -8.6595, lng: 115.1301 },
  { name: "Berawa", lat: -8.6647, lng: 115.1368 },
  { name: "Kedonganan", lat: -8.769, lng: 115.1688 },
];

// Batas usia laporan yang masih dihitung untuk status pantai (72 jam).
export const OLD_MS = 72 * 60 * 60 * 1000;

// Skala keparahan 1-4. Warna tetap, jangan diubah.
export const SEVERITY = {
  1: { label: "Bersih", color: "#2f7d5b", hint: "Air jernih, hampir tanpa sampah" },
  2: { label: "Sampah ringan", color: "#8db33a", hint: "Ada sampah tersebar, masih nyaman" },
  3: { label: "Cukup parah", color: "#e0a526", hint: "Sampah menumpuk di beberapa titik" },
  4: { label: "Darurat", color: "#d1453b", hint: "Sampah tebal atau air tercemar" },
};

export const REPORT_TYPES = {
  sampah: "Sampah pantai",
};

// Tipe sampah di pantai (khusus laporan sampah).
// Key disimpan ke laporan; label Bahasa Indonesia.
export const WASTE_TYPES = {
  plastic: { label: "Botol Plastik", icon: "🥤" },
  fishing: { label: "Jaring Ikan", icon: "⚓" },
  food: { label: "Kemasan Makanan", icon: "📦" },
  oil: { label: "Minyak / Bahan Kimia", icon: "🛢️" },
  electronic: { label: "Sampah Elektronik", icon: "🔌" },
  mixed: { label: "Campuran / Lainnya", icon: "🗑️" },
};

// Jumlah/volume sampah.
export const WASTE_AMOUNTS = {
  small: { label: "Kecil", short: "K", hint: "< 10 kg" },
  medium: { label: "Sedang", short: "S", hint: "10–50 kg" },
  large: { label: "Besar", short: "B", hint: "> 50 kg" },
};

const HOUR = 60 * 60 * 1000;
const hoursAgo = (h) => new Date(Date.now() - h * HOUR).toISOString();

const fmtDay = (offsetDays) => {
  const d = new Date(Date.now() + offsetDays * 24 * 60 * 60 * 1000);
  return d.toISOString().slice(0, 10); // YYYY-MM-DD
};

// 17 laporan seed, waktu relatif terhadap sekarang agar status 72 jam selalu hidup.
export const SEED_REPORTS = [
  {
    id: "r1",
    beach: "Kuta",
    lat: -8.7185,
    lng: 115.1688,
    severity: 3,
    type: "sampah",
    wasteType: "plastic",
    wasteAmount: "medium",
    note: "Sampah plastik menumpuk di garis pasang setelah hujan semalam.",
    photo: "",
    takenAt: hoursAgo(3),
    source: "gps",
  },
  {
    id: "r2",
    beach: "Kuta",
    lat: -8.7177,
    lng: 115.1686,
    severity: 4,
    type: "sampah",
    wasteType: "mixed",
    wasteAmount: "large",
    note: "Tumpukan sampah campur ranting di sisi selatan, butuh alat berat kecil.",
    photo: "",
    takenAt: hoursAgo(9),
    source: "peta",
  },
  {
    id: "r3",
    beach: "Seminyak",
    lat: -8.6846,
    lng: 115.1524,
    severity: 2,
    type: "sampah",
    wasteType: "food",
    wasteAmount: "small",
    note: "Sampah ringan tersebar, masih nyaman untuk berenang pagi.",
    photo: "",
    takenAt: hoursAgo(5),
    source: "exif",
  },
  {
    id: "r4",
    beach: "Canggu",
    lat: -8.6601,
    lng: 115.1309,
    severity: 3,
    type: "sampah",
    wasteType: "plastic",
    wasteAmount: "medium",
    note: "Sampah plastik menumpuk di dekat muara setelah hujan.",
    photo: "",
    takenAt: hoursAgo(26),
    source: "gps",
  },
  {
    id: "r5",
    beach: "Sanur",
    lat: -8.7105,
    lng: 115.2575,
    severity: 1,
    type: "sampah",
    wasteType: "mixed",
    wasteAmount: "small",
    note: "Pagi ini bersih, petugas sudah menyisir sejak jam 6.",
    photo: "",
    takenAt: hoursAgo(7),
    source: "exif",
  },
  {
    id: "r6",
    beach: "Jimbaran",
    lat: -8.7813,
    lng: 115.1642,
    severity: 2,
    type: "sampah",
    wasteType: "food",
    wasteAmount: "small",
    note: "Sampah kemasan tersebar dekat deretan warung, masih nyaman.",
    photo: "",
    takenAt: hoursAgo(30),
    source: "peta",
  },
  {
    id: "r7",
    beach: "Nusa Dua",
    lat: -8.7882,
    lng: 115.2304,
    severity: 1,
    type: "sampah",
    wasteType: "mixed",
    wasteAmount: "small",
    note: "Bersih dan tenang, cocok untuk keluarga.",
    photo: "",
    takenAt: hoursAgo(50),
    source: "gps",
  },
  {
    id: "r8",
    beach: "Melasti",
    lat: -8.84819,
    lng: 115.15767,
    severity: 1,
    type: "sampah",
    wasteType: "mixed",
    wasteAmount: "small",
    note: "Bersih, tebing dan pasir putih terawat.",
    photo: "",
    takenAt: hoursAgo(10),
    source: "gps",
  },
  {
    id: "r9",
    beach: "Padang Padang",
    lat: -8.8111,
    lng: 115.1037,
    severity: 1,
    type: "sampah",
    wasteType: "mixed",
    wasteAmount: "small",
    note: "Bersih, ombak bagus dan area karang terjaga.",
    photo: "",
    takenAt: hoursAgo(12),
    source: "gps",
  },
  {
    id: "r10",
    beach: "Pandawa",
    lat: -8.8454,
    lng: 115.1867,
    severity: 1,
    type: "sampah",
    wasteType: "mixed",
    wasteAmount: "small",
    note: "Bersih, cocok untuk berenang dan kano.",
    photo: "",
    takenAt: hoursAgo(8),
    source: "gps",
  },
  {
    id: "r11",
    beach: "Virgin Beach",
    lat: -8.5606,
    lng: 115.457,
    severity: 1,
    type: "sampah",
    wasteType: "mixed",
    wasteAmount: "small",
    note: "Bersih dan sepi, pasir putih alami.",
    photo: "",
    takenAt: hoursAgo(20),
    source: "gps",
  },
  {
    id: "r12",
    beach: "Suluban",
    lat: -8.8233,
    lng: 115.0855,
    severity: 1,
    type: "sampah",
    wasteType: "mixed",
    wasteAmount: "small",
    note: "Bersih di sela tebing, dijaga komunitas selancar.",
    photo: "",
    takenAt: hoursAgo(14),
    source: "gps",
  },
  {
    id: "r13",
    beach: "Balangan",
    lat: -8.7919,
    lng: 115.1235,
    severity: 1,
    type: "sampah",
    wasteType: "mixed",
    wasteAmount: "small",
    note: "Bersih, sunset terang tanpa sampah.",
    photo: "",
    takenAt: hoursAgo(16),
    source: "gps",
  },
  {
    id: "r14",
    beach: "Legian",
    lat: -8.7041,
    lng: 115.165,
    severity: 2,
    type: "sampah",
    wasteType: "plastic",
    wasteAmount: "small",
    note: "Sampah plastik tersebar di garis pantai, masih nyaman.",
    photo: "",
    takenAt: hoursAgo(6),
    source: "gps",
  },
  {
    id: "r15",
    beach: "Batu Bolong",
    lat: -8.6597,
    lng: 115.1304,
    severity: 2,
    type: "sampah",
    wasteType: "food",
    wasteAmount: "small",
    note: "Sampah kemasan ringan dekat pura, rutin dibersihkan warga.",
    photo: "",
    takenAt: hoursAgo(11),
    source: "gps",
  },
  {
    id: "r16",
    beach: "Berawa",
    lat: -8.6649,
    lng: 115.1371,
    severity: 2,
    type: "sampah",
    wasteType: "plastic",
    wasteAmount: "small",
    note: "Sampah ringan tersebar dekat muara, masih nyaman untuk jalan sore.",
    photo: "",
    takenAt: hoursAgo(9),
    source: "gps",
  },
  {
    id: "r17",
    beach: "Kedonganan",
    lat: -8.7692,
    lng: 115.1688,
    severity: 3,
    type: "sampah",
    wasteType: "mixed",
    wasteAmount: "medium",
    note: "Sampah campur menumpuk dekat pasar ikan, perlu gotong royong.",
    photo: "",
    takenAt: hoursAgo(7),
    source: "gps",
  },
];

// 5 aksi seed: 2 mendatang, 2 selesai, 1 usulan menunggu persetujuan admin.
export const SEED_EVENTS = [
  {
    id: "e1",
    title: "Bersih Pagi Kuta",
    beach: "Kuta",
    date: fmtDay(3),
    organizer: "Komunitas Pantai Kuta",
    slots: 40,
    joined: 27,
    status: "upcoming",
  },
  {
    id: "e2",
    title: "Sapuan Sampah Canggu",
    beach: "Canggu",
    date: fmtDay(7),
    organizer: "Relawan Canggu Bersih",
    slots: 25,
    joined: 25,
    status: "upcoming",
  },
  {
    id: "e3",
    title: "Aksi Teluk Jimbaran",
    beach: "Jimbaran",
    date: fmtDay(-6),
    organizer: "Teluk Lestari",
    slots: 30,
    joined: 28,
    status: "done",
    kg: 320,
    volunteers: 28,
  },
  {
    id: "e4",
    title: "Sanur Pagi Berseri",
    beach: "Sanur",
    date: fmtDay(-13),
    organizer: "Warga Sanur",
    slots: 20,
    joined: 18,
    status: "done",
    kg: 145,
    volunteers: 18,
  },
  {
    id: "e5",
    title: "Usulan Bersih Melasti",
    beach: "Melasti",
    date: fmtDay(5),
    organizer: "Warga Ungasan",
    slots: 20,
    joined: 0,
    status: "pending",
  },
];

// Usulan hasil lapangan (seed): angka dari relawan di lapangan yang menunggu
// verifikasi admin sebelum disahkan jadi hasil resmi. Lihat tabel
// result_proposals (migrasi 20260501000000) untuk mode Supabase.
export const SEED_PROPOSALS = [];
